language: cpp
compiler:
  - clang
notifications:
  email: false

before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) restricted"
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq fglrx opencl-headers libboost-program-options-dev libfftw3-dev libgtest-dev
  - sudo apt-get install libpcre3-dev julia -y

install:
  - mkdir -p bin/gTest
  - cd bin/gTest
  - cmake -DCMAKE_BUILD_TYPE=Release /usr/src/gtest
  - make
  - sudo mv libg* /usr/lib

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p deps/
  - cd deps/
  - git clone https://github.com/clMathLibraries/clFFT
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p bin/clFFT
  - cd bin/clFFT
  - cmake -DBoost_NO_SYSTEM_PATHS=OFF -DBUILD_TEST=OFF -DCMAKE_CXX_FLAGS="-std=c++11" ${TRAVIS_BUILD_DIR}/deps/clFFT/src

script:
  - make install
  - cd package/bin
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/bin/clFFT/library:${LD_LIBRARY_PATH}
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/bin/clFFT/statTimer:${LD_LIBRARY_PATH}
  #- ./Client -i
  - cd ${TRAVIS_BUILD_DIR}
  - julia -e 'Pkg.init(); Pkg.add("FactCheck"); Pkg.clone("OpenCL")'
  - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("CLFFT"))`); Pkg.pin("CLFFT"); Pkg.resolve()'
  - julia -e 'using CLFFT; @assert isdefined(:CLFFT); @assert typeof(CLFFT) === Module'
  - julia --code-coverage test/runtests.jl

after_success:
  - julia -e 'cd(Pkg.dir("CLFFT"));
              Pkg.add("Coverage");
              using Coverage;
              Coveralls.submit(Coveralls.process_folder())'
